### ISSUE TITLE
themeisle page images

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/reviewzine#44]

**Comment by claudiuvertistudio** [comment]
![ipad-and-iphone-5](https://cloud.githubusercontent.com/assets/3263086/20387213/c6e91e2a-acc7-11e6-988b-e948281a8b3e.jpg)
![ipad-and-iphone-5-s](https://cloud.githubusercontent.com/assets/3263086/20387211/c6e6fc94-acc7-11e6-8951-18d42848d45e.jpg)
![ipad-in-hands](https://cloud.githubusercontent.com/assets/3263086/20387212/c6e87da8-acc7-11e6-8914-d8d5250a5d01.jpg)
![ipad-in-hands-s](https://cloud.githubusercontent.com/assets/3263086/20387214/c6e993aa-acc7-11e6-840a-3e0562ec9c80.jpg)
![ipad-with-headphones](https://cloud.githubusercontent.com/assets/3263086/20387215/c6e9c334-acc7-11e6-9bd3-3c62d7fab338.jpg)
![ipad-with-headphones-s](https://cloud.githubusercontent.com/assets/3263086/20387216/c6eda666-acc7-11e6-8670-8a580376cc97.jpg)
![iphone-5-with-macbook](https://cloud.githubusercontent.com/assets/3263086/20387217/c7074346-acc7-11e6-8efe-a82c63f7269d.jpg)
![iphone-5-with-macbook-s](https://cloud.githubusercontent.com/assets/3263086/20387219/c7085146-acc7-11e6-8597-04dfbdd516b5.jpg)
![list-theme-movkup](https://cloud.githubusercontent.com/assets/3263086/20387218/c70839a4-acc7-11e6-9d03-39d5cf26ff42.jpg)
![mockup-macbook6](https://cloud.githubusercontent.com/assets/3263086/20387221/c709fcda-acc7-11e6-8b7a-b72b88cae3bf.jpg)
![mockup-macbook6-s](https://cloud.githubusercontent.com/assets/3263086/20387220/c7095582-acc7-11e6-8389-f33703504e89.jpg)
![realistic-macbook-mockup](https://cloud.githubusercontent.com/assets/3263086/20387222/c70b1b56-acc7-11e6-8994-29965b904f01.jpg)
![realistic-macbook-mockup-s](https://cloud.githubusercontent.com/assets/3263086/20387223/c71ffe22-acc7-11e6-900b-b38b461d8549.jpg)
![resp_design_qkefi6](https://cloud.githubusercontent.com/assets/3263086/20387225/c7240332-acc7-11e6-91e9-dc0b88af1aa6.png)
![showcase_llorix_odx3nb](https://cloud.githubusercontent.com/assets/3263086/20387224/c7242394-acc7-11e6-96df-902742d9c812.png)

**Comment by rodica-andronache** [comment]
ne mai trebuie niste poze aici ca sa punem pe langa partea aia de responsive.

Ma gandeam poate la una sa fie o poza ceva mai draguta cu partea de review http://prntscr.com/d8giaj 

Acum e asa https://themeisle.com/themes/reviewzine/
si poate una sliderul de sus.

Daca ai tu alte idei, poti sa incerci si altceva

**Comment by claudiuvertistudio** [comment]
![review](https://cloud.githubusercontent.com/assets/3263086/20426719/118e9b82-ad89-11e6-912d-364d3dadba35.png)
![slider](https://cloud.githubusercontent.com/assets/3263086/20426718/118e3c78-ad89-11e6-8244-4840fa246272.png)
