### ISSUE TITLE
Arrange demo page

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/reviewzine#48]
https://demo.themeisle.com/reviewzine/ 
The theme is designed for reviews, so maybe try this approach for the demo

**Comment by ineagu** [comment]
we have the psd here as well, we can try to follow the original design on demo

**Comment by claudiuvertistudio** [comment]
I think it's done

**Comment by rodica-andronache** [comment]
I think that on the contact page, there are some remaining code causing this http://prntscr.com/d8fpqr
and in the sidebar, is this how you wanted to have the images http://prntscr.com/d8fqgk ? smaller than all the other widgets?

**Comment by claudiuvertistudio** [comment]
for this http://prntscr.com/d8fpqr I have created a issue
for http://prntscr.com/d8fqgk the banner have standard size 300x250px. maybe it should be centered
